@echo off
echo Starting AI Insight Dashboard Admin...
echo.
echo Starting Spring Boot backend on port 8080...
start cmd /k "cd %~dp0 && mvn spring-boot:run"
echo.
echo Waiting for backend to initialize...
timeout /t 15 /nobreak
echo Starting React frontend on port 8080...
start cmd /k "cd %~dp0client && npm start"
echo.
echo Application is starting. Please wait...
echo Access the admin panel at: http://localhost:8080
